---

- name: ensure fail2ban is installed
  yum: name=fail2ban state=latest

- name: ensure fail2ban service is enabled and started
  service: name=fail2ban enabled=yes state=started

- name: create local jail for fail2ban
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local backup=yes
  notify: restart fail2ban
