---

- name: restart apache
  service: name=httpd state=restarted

- name: restart firewall
  service: name=firewalld state=restarted

- name: restart supervisor
  service: name=supervisord state=restarted
